version: '3'
services:
  quiz:
    image: quiz
    stdin_open: true
    ports:
      - "5173:5173"
    networks:
      - quiz-app

  quiz-backend:
    image: quiz-backend
    ports:
      - "3005:3005"
    networks:
      - quiz-app
networks:
  quiz-app:
    driver: bridge